# Generated by Django 4.2.14 on 2026-08-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('recommended_age', models.CharField(blank=True, max_length=60)),
                ('doses_in_series', models.PositiveIntegerField(default=1)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sequence', 'code'),
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('date_given', models.DateField(default=django.utils.timezone.localdate)),
                ('batch_no', models.CharField(blank=True, max_length=40)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('given_by', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='vaccination.vaccine')),
            ],
            options={
                'ordering': ('-date_given', '-id'),
            },
        ),
    ]
