# Generated by Django 4.2.14 on 2026-07-20 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('suppliers', '0002_supplier_balance_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('name', 'hospital'), name='uniq_supplier_name_per_hospital'),
        ),
    ]
