# Generated by Django 4.2.14 on 2026-07-02 13:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('ULTRASOUND', 'Ultrasound'), ('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ECG', 'ECG'), ('ECHO', 'Echocardiography'), ('MAMMO', 'Mammography'), ('OTHER', 'Other')], default='ULTRASOUND', max_length=20)),
                ('study_name', models.CharField(help_text='e.g. Abdominal Ultrasound, Chest X-Ray (PA view)', max_length=150)),
                ('clinical_note', models.TextField(blank=True, help_text='Referring clinical note / reason for the scan')),
                ('study_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Reported', 'Reported'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('findings', models.TextField(blank=True)),
                ('impression', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imaging/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='patients.patient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_performed', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_referred', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imaging Study',
                'verbose_name_plural': 'Imaging Studies',
                'ordering': ['-study_date'],
            },
        ),
    ]
