# Generated by Django 4.2.14 on 2026-07-03 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality', models.CharField(choices=[('ULTRASOUND', 'Ultrasound'), ('XRAY', 'X-Ray'), ('CT', 'CT Scan'), ('MRI', 'MRI'), ('ECG', 'ECG'), ('ECHO', 'Echocardiography'), ('MAMMO', 'Mammography'), ('OTHER', 'Other')], default='ULTRASOUND', max_length=20)),
                ('name', models.CharField(help_text='e.g. Abdominal Ultrasound, Chest X-Ray (PA)', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('modality', 'name'),
            },
        ),
    ]
