# Generated by Django 4.2.14 on 2026-07-14 11:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imaging', '0002_scantype'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='payment_collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_imaging_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagingstudy',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20),
        ),
    ]
