# Generated by Django 4.2.14 on 2026-08-13 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_desktopbackup'),
        ('imaging', '0004_imagingstudy_cancel_reason_imagingstudy_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantype',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
    ]
