# Generated by Django 4.2.14 on 2026-08-20 11:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging', '0006_split_catalogue_per_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingstudy',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='scantype',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
