# Generated by Django 4.2.14 on 2026-07-03 07:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('RENT', 'Rent'), ('SALARY', 'Salaries / Wages'), ('UTILITIES', 'Utilities (electricity, water, gas)'), ('SUPPLIES', 'Supplies / Consumables'), ('MAINTENANCE', 'Repairs & Maintenance'), ('MARKETING', 'Marketing'), ('TAX', 'Tax / Govt fees'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(default='CASH', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
