# Generated by Django 4.2.14 on 2026-07-03 07:24

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('opening', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('counted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
