# Generated by Django 4.2.14 on 2026-07-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_cashclosing_hospital_expense_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('VOID', 'Void / Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
