# Generated by Django 4.2.14 on 2026-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('hospital', 'number'), name='uniq_invoice_number_per_hospital'),
        ),
    ]
