# Generated by Django 4.2.14 on 2026-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='claim_number',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='claim_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Submission'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PAID', 'Paid by Panel'), ('REJECTED', 'Rejected')], default='', max_length=12),
        ),
    ]
