# Generated by Django 4.2.14 on 2026-08-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_claim_number_invoice_claim_status'),
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='panels.panel'),
        ),
    ]
