# Generated by Django 4.2.14 on 2026-08-05 13:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_panel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='panel_settled',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
