# Generated by Django 4.2.14 on 2026-07-13 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('opd', '0003_doctor_share_percent_doctorpayout'),
        ('patients', '0002_patient_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('admission_reason', models.TextField()),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('discharge_notes', models.TextField(blank=True)),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='opd.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('clinical_notes', models.TextField()),
                ('prescription_updates', models.TextField(blank=True)),
                ('vitals_temp', models.CharField(blank=True, max_length=50, verbose_name='Temperature (°F)')),
                ('vitals_bp', models.CharField(blank=True, max_length=50, verbose_name='Blood Pressure')),
                ('vitals_pulse', models.CharField(blank=True, max_length=50, verbose_name='Pulse Rate (bpm)')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='ipd.ward')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='ipd.bed'),
        ),
        migrations.AddField(
            model_name='admission',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
    ]
