# Generated by Django 4.2.14 on 2026-07-13 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('General Male', 'General Ward (Male)'), ('General Female', 'General Ward (Female)'), ('ICU', 'Intensive Care Unit (ICU)'), ('CCU', 'Coronary Care Unit (CCU)'), ('Paediatric', 'Paediatric (Kids) Ward'), ('Surgical', 'Surgical Ward'), ('Maternity', 'Maternity Ward'), ('Private Room', 'Private Room'), ('Semi-Private Room', 'Semi-Private Room')], default='General Male', max_length=50),
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150, verbose_name='Medicine Name')),
                ('dosage', models.CharField(help_text='e.g. 500mg, 1 tablet, 2 puffs', max_length=100)),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Administered Date & Time')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_administered', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
        ),
    ]
