# Generated by Django 4.2.14 on 2026-07-22 11:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_medicine_unique_together'),
        ('ipd', '0003_admissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='medicine',
            field=models.ForeignKey(blank=True, help_text='Pharmacy catalogue item, when the drug came from stock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_administrations', to='inventory.medicine'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Units taken from stock (tablets, vials, bottles)'),
        ),
        migrations.AddField(
            model_name='medicationlog',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
