# Generated by Django 4.2.14 on 2026-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0004_medicationlog_medicine_medicationlog_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='source',
            field=models.CharField(choices=[('PHARMACY', 'Hospital pharmacy stock'), ('PATIENT', "Patient's own supply (brought from outside)")], default='PHARMACY', max_length=20, verbose_name='Where the medicine came from'),
        ),
        migrations.AlterField(
            model_name='medicationlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Units given (tablets, vials, bottles)'),
        ),
    ]
