# Generated by Django 4.2.14 on 2026-07-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_invoice_status'),
        ('ipd', '0005_medicationlog_source_alter_medicationlog_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharge_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice'),
        ),
    ]
