# Generated by Django 4.2.14 on 2026-08-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipd', '0006_admission_discharge_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='in_charge',
            field=models.ForeignKey(blank=True, help_text='Ward In-charge (senior nurse who runs the ward)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wards_in_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PatientAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ipd.admission')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', 'shift'),
            },
        ),
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('duty', models.CharField(choices=[('INCHARGE', 'Shift In-charge'), ('STAFF', 'Staff Nurse')], default='STAFF', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_shifts', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='ipd.ward')),
            ],
            options={
                'ordering': ('-date', 'shift'),
            },
        ),
        migrations.AddConstraint(
            model_name='patientallocation',
            constraint=models.UniqueConstraint(fields=('admission', 'date', 'shift'), name='uniq_admission_date_shift'),
        ),
        migrations.AddConstraint(
            model_name='nurseshift',
            constraint=models.UniqueConstraint(fields=('nurse', 'date', 'shift'), name='uniq_nurse_date_shift'),
        ),
    ]
