# Generated by Django 4.2.14 on 2026-08-05 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipd', '0007_ward_in_charge_patientallocation_nurseshift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°F)')),
                ('pulse', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulse (bpm)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory rate (/min)')),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Systolic BP')),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Diastolic BP')),
                ('spo2', models.PositiveIntegerField(blank=True, null=True, verbose_name='SpO₂ (%)')),
                ('consciousness', models.CharField(choices=[('A', 'Alert'), ('V', 'Responds to voice'), ('P', 'Responds to pain'), ('U', 'Unresponsive')], default='A', max_length=1, verbose_name='Consciousness (AVPU)')),
                ('pain_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pain score (0–10)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Blood glucose (mg/dL)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-taken_at',),
            },
        ),
        migrations.CreateModel(
            name='FluidBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('direction', models.CharField(choices=[('IN', 'Intake'), ('OUT', 'Output')], max_length=3)),
                ('kind', models.CharField(help_text='e.g. IV fluid, Oral, NG feed, Urine, Drain, Vomit', max_length=40)),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Volume (mL)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluid_entries', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fluid balance entries',
                'ordering': ('-recorded_at',),
            },
        ),
    ]
