# Generated by Django 4.2.14 on 2026-08-05 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
        ('ipd', '0008_vitalsobservation_fluidbalanceentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], help_text='The shift being handed over', max_length=10)),
                ('situation', models.TextField(help_text='Why the patient is here / current problem')),
                ('background', models.TextField(blank=True)),
                ('assessment', models.TextField(blank=True, help_text='How they are now — obs, concerns')),
                ('recommendation', models.TextField(blank=True, help_text='What the next shift must do')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='ipd.admission')),
                ('from_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], max_length=10)),
                ('note', models.TextField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-noted_at',),
            },
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('TURN', 'Positioning / turning'), ('HYGIENE', 'Hygiene / bed bath'), ('CATHETER', 'Catheter care'), ('IV', 'IV site care'), ('WOUND', 'Wound / dressing'), ('MOBILISE', 'Mobilisation'), ('FEED', 'Feeding / NG'), ('OTHER', 'Other')], max_length=12)),
                ('done_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='ipd.admission')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
            options={
                'ordering': ('-done_at',),
            },
        ),
    ]
