"""Record whether a ward dose actually came off pharmacy stock.

The chart used to infer it from `unit_price > 0`, which is a different question:
an unpriced catalogue medicine was deducted from inventory while the chart said
it was not issued at all.

Existing rows are backfilled from the best evidence there is — a pharmacy source
with a catalogue medicine and no shortage marker in the notes. Schema then data
in one migration is the allowed order (see CLAUDE.md); data then schema is not.
"""
# Generated by Django 4.2.14 on 2026-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipd', '0012_shift_fk_finish'),
    ]

    def _backfill(apps, schema_editor):
        MedicationLog = apps.get_model('ipd', 'MedicationLog')
        (MedicationLog.objects
         .filter(source='PHARMACY', medicine__isnull=False)
         .exclude(notes__contains='not deducted')
         .update(stock_deducted=True))

    operations = [
        migrations.AddField(
            model_name='medicationlog',
            name='stock_deducted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
    ]
