# Generated by Django 4.2.14 on 2026-08-05 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0011_invoice_panel_settled'),
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
        ('patients', '0007_patient_panel_coverage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(blank=True, max_length=255)),
                ('lmp', models.DateField(blank=True, help_text='Last menstrual period', null=True)),
                ('gravida', models.PositiveIntegerField(default=1)),
                ('para', models.PositiveIntegerField(default=0)),
                ('abortions', models.PositiveIntegerField(default=0)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('high_risk', models.BooleanField(default=False)),
                ('risk_notes', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed')], default='ONGOING', max_length=10)),
                ('registered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancies', to='patients.patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_on',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_type', models.CharField(choices=[('NORMAL', 'Normal (SVD)'), ('CSECTION', 'C-Section'), ('ASSISTED', 'Assisted (forceps / vacuum)'), ('BREECH', 'Breech')], default='NORMAL', max_length=10)),
                ('outcome', models.CharField(choices=[('LIVE', 'Live birth'), ('STILL', 'Stillbirth')], default='LIVE', max_length=6)),
                ('notes', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.doctor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='patients.patient')),
                ('pregnancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='maternity.pregnancy')),
            ],
            options={
                'ordering': ('-delivered_at',),
            },
        ),
        migrations.CreateModel(
            name='Birth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], default='M', max_length=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ALIVE', 'Alive'), ('DECEASED', 'Deceased')], default='ALIVE', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='births', to='maternity.delivery')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='AntenatalVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('bp', models.CharField(blank=True, max_length=20)),
                ('fundal_height', models.CharField(blank=True, max_length=20)),
                ('fhr', models.CharField(blank=True, max_length=20)),
                ('complaints', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('next_visit', models.DateField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('pregnancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='maternity.pregnancy')),
                ('seen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.doctor')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
