# Generated by Django 4.2.14 on 2026-08-20 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
