# Generated by Django 4.2.14 on 2026-08-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='allowed_monthly_leaves',
            field=models.IntegerField(default=2, help_text='Monthly allowed paid leaves'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='deduction_per_absent_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed daily deduction rate, or leave empty for auto (salary / 30)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='enable_absence_deduction',
            field=models.BooleanField(default=True, help_text='Enable dynamic salary deduction for absences/excess leaves'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/'),
        ),
    ]
