# Generated by Django 4.2.14 on 2026-08-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_desktopbackup'),
        ('hr', '0002_staffprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning, Night, Shift A', max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(help_text='May be earlier than the start — a night shift crossing midnight is normal.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Position in the roster grid (lowest first).')),
                ('is_active', models.BooleanField(default=True, help_text='Retired shifts stay here so old rosters still read correctly.')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='saas.hospital')),
            ],
            options={
                'ordering': ('order', 'start_time'),
            },
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('hospital', 'name'), name='uniq_shift_name_per_hospital'),
        ),
    ]
