# Generated by Django 4.2.14 on 2026-08-18 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_desktopbackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text="The machine's serial number — in its menu under Info / Device Info, and usually printed on the back.", max_length=40, unique=True)),
                ('name', models.CharField(help_text='e.g. Main Gate', max_length=60)),
                ('location', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to stop accepting punches from this machine without losing the ones it has already sent.')),
                ('timezone_offset', models.SmallIntegerField(default=5, help_text='Hours ahead of UTC that the machine is set to. Pakistan is 5.')),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('punches_received', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UnknownDeviceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=40, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('hits', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-last_seen',),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Entered by staff'), ('DEVICE', 'From the attendance machine')], default='MANUAL', max_length=8),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='biometric_id',
            field=models.CharField(blank=True, help_text='Enrolment number on the fingerprint machine (the number the device shows next to this person, not their staff id).', max_length=32),
        ),
        migrations.CreateModel(
            name='BiometricPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(help_text='Enrolment number exactly as the machine sent it.', max_length=32)),
                ('punched_at', models.DateTimeField()),
                ('raw', models.CharField(blank=True, max_length=200)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='hr.biometricdevice')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biometric_punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-punched_at',),
                'indexes': [models.Index(fields=['hospital', 'punched_at'], name='hr_biometri_hospita_90fff5_idx')],
                'unique_together': {('device', 'device_user_id', 'punched_at')},
            },
        ),
    ]
