# Generated by Django 4.2.14 on 2026-08-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('OUT', 'Referred Out'), ('IN', 'Referred In')], default='OUT', max_length=3)),
                ('facility', models.CharField(help_text='The other facility (sent to / received from)', max_length=200)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('receiving_doctor', models.CharField(blank=True, max_length=150)),
                ('reason', models.CharField(max_length=255)),
                ('clinical_summary', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('referral_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='opd.doctor')),
            ],
            options={
                'ordering': ('-referral_date', '-id'),
            },
        ),
    ]
