# Generated by Django 4.2.14 on 2026-08-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=20)),
                ('deceased_name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_text', models.CharField(blank=True, help_text='e.g. 62 years, 3 days', max_length=40)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('father_husband_name', models.CharField(blank=True, max_length=150)),
                ('date_of_death', models.DateField()),
                ('time_of_death', models.TimeField(blank=True, null=True)),
                ('place_of_death', models.CharField(blank=True, max_length=200)),
                ('cause_of_death', models.CharField(max_length=255)),
                ('secondary_causes', models.TextField(blank=True)),
                ('manner', models.CharField(blank=True, help_text='Natural / accident / etc.', max_length=120)),
                ('is_mlc', models.BooleanField(default=False, verbose_name='Medico-legal case')),
                ('next_of_kin', models.CharField(blank=True, max_length=150)),
                ('next_of_kin_cnic', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('registered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_certificates', to='patients.patient')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_certs_registered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BirthCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(blank=True, db_index=True, max_length=20)),
                ('child_name', models.CharField(blank=True, help_text='Leave blank if not yet named', max_length=150)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=200)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_cnic', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('father_cnic', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('registered_on', models.DateField(default=django.utils.timezone.localdate)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registered_on', '-id'),
            },
        ),
    ]
