# Generated by Django 4.2.14 on 2026-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('WHOLESALE', 'Wholesale Operator'), ('LABTECH', 'Lab Technician'), ('SONOGRAPHER', 'Sonographer'), ('ACCOUNTANT', 'Accountant')], default='PHARMACIST', max_length=20),
        ),
    ]
