# Generated by Django 4.2.14 on 2026-07-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_features',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
