# Generated by Django 4.2.14 on 2026-07-13 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('accounts', '0003_user_custom_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='saas.hospital'),
        ),
    ]
