# Generated by Django 4.2.14 on 2026-08-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('RECEPTIONIST', 'Receptionist'), ('DOCTOR', 'Doctor'), ('NURSE', 'Ward Staff / Nurse'), ('PHARMACIST', 'Pharmacist'), ('WHOLESALE', 'Wholesale Operator'), ('LABTECH', 'Lab Technician'), ('SONOGRAPHER', 'Sonographer'), ('ACCOUNTANT', 'Accountant'), ('NOLOGIN', 'No system access')], default='PHARMACIST', max_length=20),
        ),
    ]
