# Generated by Django 4.2.14 on 2026-07-13 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('ipd', '0001_initial'),
        ('opd', '0003_doctor_share_percent_doctorpayout'),
        ('patients', '0002_patient_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
            options={
                'verbose_name_plural': 'Surgery Categories',
            },
        ),
        migrations.CreateModel(
            name='SurgeryProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('standard_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='ot.surgerycategory')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('surgical_team', models.TextField(blank=True, help_text='List other doctors, assistants, anesthetist, nurses etc.')),
                ('anesthesia_type', models.CharField(blank=True, max_length=100)),
                ('operation_notes', models.TextField()),
                ('outcome', models.CharField(choices=[('Successful', 'Successful'), ('Complications', 'Complications'), ('Failed', 'Failed')], default='Successful', max_length=50)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='ipd.admission')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('lead_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries_led', to='opd.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ot.surgeryprocedure')),
            ],
        ),
    ]
