# Generated by Django 4.2.14 on 2026-07-20 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
        ('ot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Indication / reason for surgery')),
                ('urgency', models.CharField(choices=[('Elective', 'Elective (planned)'), ('Urgent', 'Urgent'), ('Emergency', 'Emergency')], default='Elective', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_advices', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_requests', to='patients.patient')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ot.surgeryprocedure')),
                ('surgery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_request', to='ot.surgeryrecord')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
