# Generated by Django 4.2.14 on 2026-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ot', '0002_surgeryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryprocedure',
            name='anesthesia_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Anaesthetist's fee", max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryprocedure',
            name='consumables_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sutures, disposables, implants billed to the patient', max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryprocedure',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Your own cost. Optional; used by the Profit by Module report.', max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryprocedure',
            name='ot_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Theatre / operating room charge', max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='anesthesia_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='consumables_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='ot_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='surgeryrecord',
            name='surgeon_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
