# Generated by Django 4.2.14 on 2026-08-17 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_invoice_panel_settled'),
        ('ot', '0004_backfill_surgery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeryrecord',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='billing.invoice'),
        ),
    ]
