# Generated by Django 4.2.14 on 2026-07-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='PharmaDost', max_length=60)),
                ('brand_tagline', models.CharField(blank=True, default='Hospital & Pharmacy', max_length=80)),
                ('logo_text', models.CharField(default='P', help_text='1–2 letters shown in the logo badge when no image is set', max_length=2)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('primary_color', models.CharField(default='#4f46e5', help_text='Main theme colour (hex, e.g. #4f46e5)', max_length=7)),
                ('accent_color', models.CharField(default='#0ea5a4', help_text='Secondary/gradient colour (hex)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
