# Generated by Django 4.2.14 on 2026-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Shown on printed bills & reports', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='license_no',
            field=models.CharField(blank=True, default='', help_text='Drug sale licence / registration no. (optional)', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Thank you! Get well soon.', help_text='Message printed at the bottom of bills', max_length=200),
        ),
    ]
