# Generated by Django 4.2.14 on 2026-07-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0003_sitesettings_address_sitesettings_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=None, help_text='List of enabled module keys (null = all)', null=True),
        ),
    ]
