# Generated by Django 4.2.14 on 2026-07-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0004_sitesettings_enabled_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='print_theme',
            field=models.CharField(choices=[('classic', 'Classic Letterhead'), ('modern', 'Modern Colour Band'), ('elegant', 'Elegant Serif'), ('minimal', 'Clean Minimal')], default='classic', help_text='Design used for printed lab reports, bills & receipts', max_length=20),
        ),
    ]
