# Generated by Django 4.2.14 on 2026-07-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_sitesettings_print_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='print_theme',
            field=models.CharField(choices=[('classic', 'Classic Letterhead'), ('modern', 'Modern Colour Band'), ('elegant', 'Elegant Serif'), ('minimal', 'Clean Minimal'), ('letterhead', 'My pre-printed letterhead (blank top)')], default='classic', help_text='Design used for printed lab reports, bills & receipts', max_length=20),
        ),
    ]
