# Generated by Django 4.2.14 on 2026-07-15 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('user_mgmt', '0006_alter_sitesettings_print_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hospital',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='saas.hospital'),
        ),
    ]
