# Generated by Django 4.2.14 on 2026-07-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0008_resync_sitesettings_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_doctor_to_pharmacy',
            field=models.BooleanField(default=True, help_text="Show the prescribing doctor's name to pharmacy staff on the POS pending-prescription list"),
        ),
    ]
