# Generated by Django 4.2.14 on 2026-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0009_sitesettings_show_doctor_to_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mrn_last_number',
            field=models.PositiveIntegerField(default=0, help_text='Last patient number issued. Raise it to skip ahead; lowering it risks colliding with existing MRNs.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mrn_prefix',
            field=models.CharField(blank=True, default='', help_text='Letters in front of the patient number, e.g. SGH in SGH-000001. Leave blank to derive it from the brand name.', max_length=6),
        ),
    ]
