# Generated by Django 4.2.14 on 2026-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0010_sitesettings_mrn_last_number_sitesettings_mrn_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='Sehatyar', max_length=60),
        ),
    ]
