# Generated by Django 4.2.14 on 2026-08-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0011_alter_sitesettings_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Follow the device')], default='light', help_text='Light or dark by default for everyone (each device can still switch)', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_enabled',
            field=models.BooleanField(default=True, help_text="Show a 'Send on WhatsApp' button on patient bills"),
        ),
    ]
