# Generated by Django 4.2.14 on 2026-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0012_sitesettings_default_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_bill_qr',
            field=models.BooleanField(default=True, help_text='Print a scannable QR of the bill summary on printed bills'),
        ),
    ]
