# Generated by Django 4.2.14 on 2026-08-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0013_sitesettings_show_bill_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_last_number',
            field=models.PositiveIntegerField(default=0, help_text='Last invoice number issued. With the year switched on the count restarts each calendar year.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_number_year',
            field=models.PositiveIntegerField(default=0, help_text='The year the counter is currently running in (used to restart numbering each year). Managed automatically.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_prefix',
            field=models.CharField(blank=True, default='INV', help_text='Letters in front of the invoice number, e.g. INV in INV-2026-00001.', max_length=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_year_in_number',
            field=models.BooleanField(default=True, help_text='Put the year in the invoice number (INV-2026-00001). Off gives INV-00001.'),
        ),
    ]
