# Generated by Django 4.2.14 on 2026-08-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0014_sitesettings_invoice_last_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='Rs', help_text='Shown before every amount, e.g. Rs, ₨, PKR, $, ﷼. Just the symbol/text.', max_length=8),
        ),
    ]
