# Generated by Django 4.2.14 on 2026-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0015_sitesettings_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bill_rounding',
            field=models.CharField(choices=[('none', 'No rounding'), ('1', 'Nearest 1'), ('5', 'Nearest 5'), ('10', 'Nearest 10')], default='none', help_text="Round the final payable to the nearest 1/5/10 (handy where small coins aren't used).", max_length=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='A standing discount taken off every pharmacy sale, as a %. 0 = none. A cashier can still override it on the counter.', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax/GST added to every bill, as a %. 0 = no tax.', max_digits=5),
        ),
    ]
