# Generated by Django 4.2.14 on 2026-08-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0016_sitesettings_bill_rounding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='accent_color',
            field=models.CharField(default='#059669', help_text='Secondary/gradient colour (hex)', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0891b2', help_text='Main theme colour (hex, e.g. #4f46e5)', max_length=7),
        ),
    ]
