# Generated by Django 4.2.14 on 2026-07-02 10:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_purchaseorder_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('DROPS', 'Drops'), ('CREAM', 'Cream / Ointment'), ('INHALER', 'Inhaler'), ('SACHET', 'Sachet'), ('SUPPOSITORY', 'Suppository'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='generic_name',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pack_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='rack_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='reorder_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medicine',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
