# Generated by Django 4.2.14 on 2026-07-02 11:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_purchasereturn_stockadjustment_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
