# Generated by Django 4.2.14 on 2026-07-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('inventory', '0010_purchaserequest_purchaserequestitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
    ]
