# Generated by Django 4.2.14 on 2026-07-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        ('inventory', '0011_medicine_hospital_purchaseorder_hospital_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together={('name', 'brand', 'hospital')},
        ),
    ]
