# Generated by Django 4.2.14 on 2026-08-05 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
        ('billing', '0011_invoice_panel_settled'),
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('triage', models.CharField(choices=[('RED', 'Red — Immediate (resuscitation)'), ('YELLOW', 'Yellow — Urgent'), ('GREEN', 'Green — Non-urgent'), ('BLACK', 'Black — Deceased / expectant')], default='YELLOW', max_length=8)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('mode_of_arrival', models.CharField(choices=[('WALKIN', 'Walk-in'), ('AMBULANCE', 'Ambulance'), ('POLICE', 'Police'), ('REFERRED', 'Referred'), ('OTHER', 'Other')], default='WALKIN', max_length=10)),
                ('brought_by', models.CharField(blank=True, max_length=255)),
                ('is_mlc', models.BooleanField(default=False)),
                ('mlc_no', models.CharField(blank=True, max_length=50)),
                ('pulse', models.CharField(blank=True, max_length=20)),
                ('bp', models.CharField(blank=True, max_length=20)),
                ('temp', models.CharField(blank=True, max_length=20)),
                ('spo2', models.CharField(blank=True, max_length=20)),
                ('disposition', models.CharField(choices=[('WAITING', 'Waiting for doctor'), ('IN_TREATMENT', 'In treatment'), ('ADMITTED', 'Admitted (IPD)'), ('DISCHARGED', 'Discharged'), ('REFERRED', 'Referred out'), ('LAMA', 'Left against medical advice'), ('EXPIRED', 'Expired')], default='WAITING', max_length=14)),
                ('disposition_notes', models.TextField(blank=True)),
                ('disposed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='opd.doctor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emergency_cases', to='patients.patient')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
