# Generated by Django 4.2.14 on 2026-07-14 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_medicine_unique_together'),
        ('prescriptions', '0002_rxpreset_rxpresetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='custom_medicine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine'),
        ),
    ]
