# Generated by Django 4.2.14 on 2026-07-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Dispensed'), ('DISPENSED', 'Dispensed')], default='PENDING', max_length=20),
        ),
    ]
