# Generated by Django 4.2.14 on 2026-08-21 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_doctor_hospital'),
        ('inventory', '0013_medicine_cost_price'),
        ('prescriptions', '0005_prescription_cancel_reason_prescription_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rxpreset',
            name='complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rxpreset',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rxpreset',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rx_presets', to='opd.doctor'),
        ),
        migrations.AddField(
            model_name='rxpreset',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rxpresetitem',
            name='custom_medicine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='rxpresetitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.medicine'),
        ),
    ]
