# Generated by Django 4.2.14 on 2026-08-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_desktopbackup'),
        ('prescriptions', '0006_rxpreset_complaint_rxpreset_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rxpreset',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital'),
        ),
    ]
