# Generated by Django 4.2.14 on 2026-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_backfill_auditlog_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.CharField(blank=True, db_index=True, max_length=45),
        ),
    ]
