# Generated by Django 4.2.14 on 2026-08-06 12:48

from django.db import migrations, models
import saas.models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_name', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to=saas.models._backup_upload_to)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
