# Generated by Django 4.2.14 on 2026-08-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('consent_type', models.CharField(choices=[('SURGERY', 'Surgery / Operation'), ('ANAESTHESIA', 'Anaesthesia'), ('PROCEDURE', 'Procedure / Investigation'), ('BLOOD', 'Blood Transfusion'), ('HIV', 'HIV Testing'), ('GENERAL', 'General / Admission'), ('MLC', 'Medico-legal')], default='GENERAL', max_length=12)),
                ('body', models.TextField(help_text='Consent wording. Shown on the printed form for signature.')),
                ('is_active', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
            ],
            options={
                'ordering': ('consent_type', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('SURGERY', 'Surgery / Operation'), ('ANAESTHESIA', 'Anaesthesia'), ('PROCEDURE', 'Procedure / Investigation'), ('BLOOD', 'Blood Transfusion'), ('HIV', 'HIV Testing'), ('GENERAL', 'General / Admission'), ('MLC', 'Medico-legal')], default='GENERAL', max_length=12)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('procedure_name', models.CharField(blank=True, max_length=200)),
                ('signed_by', models.CharField(blank=True, help_text='Patient, or guardian if unable', max_length=150)),
                ('relation', models.CharField(blank=True, help_text='Relation to patient, if a guardian signs', max_length=60)),
                ('witness_name', models.CharField(blank=True, max_length=150)),
                ('signed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consent.consenttemplate')),
            ],
            options={
                'ordering': ('-signed_on', '-id'),
            },
        ),
    ]
