# Generated by Django 4.2.14 on 2026-07-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_labtest_normal_range_alter_labtest_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.AlterField(
            model_name='testorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sample Collected', 'Sample Collected'), ('Result Entered', 'Result Entered'), ('Verified', 'Verified'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
