# Generated by Django 4.2.14 on 2026-07-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_delete_patient_alter_testorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sample Collected', 'Sample Collected'), ('Result Entered', 'Result Entered'), ('Completed', 'Completed'), ('Verified', 'Verified'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
