# Generated by Django 4.2.14 on 2026-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_testorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='testresult',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
