# Generated by Django 4.2.14 on 2026-08-17 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_split_catalogue_per_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
