# Generated by Django 4.2.14 on 2026-07-02 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('pmdc_no', models.CharField(blank=True, max_length=50)),
                ('opd_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('followup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('followup_valid_days', models.PositiveIntegerField(default=7)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('token_no', models.PositiveIntegerField(default=1)),
                ('visit_type', models.CharField(choices=[('OPD', 'OPD'), ('FOLLOWUP', 'Follow-up'), ('EMERGENCY', 'Emergency')], default='OPD', max_length=12)),
                ('status', models.CharField(choices=[('BOOKED', 'Booked'), ('ARRIVED', 'Arrived'), ('IN_CONSULT', 'In Consult'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='opd.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient')),
            ],
            options={
                'ordering': ('appointment_date', 'token_no'),
            },
        ),
    ]
