# Generated by Django 4.2.14 on 2026-07-02 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CONSULT', 'Consultation / Diagnosis'), ('PROCEDURE', 'Procedure'), ('OPERATION', 'Operation / Surgery'), ('ULTRASOUND', 'Ultrasound'), ('XRAY', 'X-Ray'), ('ECG', 'ECG / Echo'), ('VACCINE', 'Vaccination'), ('OTHER', 'Other')], default='CONSULT', max_length=12)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('title', models.CharField(help_text='e.g. "Appendectomy", "Abdominal Ultrasound"', max_length=200)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True, help_text='Findings, operation notes, procedure details…')),
                ('bp', models.CharField(blank=True, max_length=20, verbose_name='Blood Pressure')),
                ('pulse', models.CharField(blank=True, max_length=20)),
                ('temperature', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_records', to='opd.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_records', to='opd.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_records', to='patients.patient')),
            ],
            options={
                'ordering': ('-date', '-created_at'),
            },
        ),
    ]
