# Generated by Django 4.2.14 on 2026-08-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_doctor_hospital'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date', 'status'], name='idx_appt_doc_dt_st'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date', 'status'], name='idx_appt_dt_st'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'created_at'], name='idx_appt_pat_cr'),
        ),
    ]
