# Generated by Django 4.2.14 on 2026-08-21 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_appointment_idx_appt_doc_dt_st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='track_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
