# Generated by Django 4.2.14 on 2026-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mrn',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('mrn', ''), _negated=True), fields=('hospital', 'mrn'), name='uniq_mrn_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('hospital__isnull', True), models.Q(('mrn', ''), _negated=True)), fields=('mrn',), name='uniq_mrn_without_hospital'),
        ),
    ]
