# Generated by Django 4.2.14 on 2026-08-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
        ('patients', '0005_seed_mrn_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='panels.panel'),
        ),
        migrations.AddField(
            model_name='patient',
            name='panel_member_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
