# Generated by Django 4.2.14 on 2026-08-05 13:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_panel_patient_panel_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='panel_coverage_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
