# Generated by Django 4.2.14 on 2026-08-17 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_strip_doctor_titles'),
        ('saas', '0002_desktopbackup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0007_patient_panel_coverage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=patients.models._document_path)),
                ('kind', models.CharField(choices=[('RX', 'Prescription'), ('LAB', 'Lab report'), ('SCAN', 'Scan / X-ray report'), ('DISCHARGE', 'Discharge / referral letter'), ('ID', 'ID card / Sehat Card'), ('CONSENT', 'Signed consent'), ('OTHER', 'Other')], default='RX', max_length=12)),
                ('title', models.CharField(blank=True, help_text='Optional — "Dr. Sara, BP medicines"', max_length=120)),
                ('doc_date', models.DateField(default=django.utils.timezone.localdate, help_text='The date on the paper, not today')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='opd.appointment')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_documents', to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-doc_date', '-uploaded_at'),
            },
        ),
    ]
