# Generated by Django 4.2.14 on 2026-08-17 13:59

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdocument',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=patients.models._thumb_path),
        ),
    ]
