# Generated by Django 4.2.14 on 2026-08-21 09:55

from django.db import migrations, models
import uuid


def backfill_tokens(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for p in Patient.objects.filter(portal_token__isnull=True):
        p.portal_token = uuid.uuid4()
        p.save(update_fields=['portal_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_document_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='portal_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(backfill_tokens, reverse_code=migrations.RunPython.noop),
    ]
