# Generated by Django 4.2.14 on 2026-08-21 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_regenerate_unique_portal_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalLookupAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['ip', 'at'], name='patients_po_ip_3d88cc_idx')],
            },
        ),
    ]
