# Generated by Django 4.2.14 on 2026-08-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0005_doctorschedule_doctoravailabilityoverride_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saas', '0001_initial'),
        ('patients', '0007_patient_panel_coverage_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinical_note', models.CharField(blank=True, max_length=255)),
                ('diagnosed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_diagnoses', to='diagnosis.diagnosiscode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='opd.doctor')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saas.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='patients.patient')),
            ],
            options={
                'ordering': ('-diagnosed_on', '-id'),
            },
        ),
    ]
