# Generated by Django 4.2.14 on 2026-08-17 12:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saas', '0002_desktopbackup'),
        ('billing', '0011_invoice_panel_settled'),
        ('patients', '0007_patient_panel_coverage_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(help_text='Number plate, e.g. LEA-1234', max_length=30)),
                ('label', models.CharField(blank=True, help_text='What staff call it — "Ambulance 1", "ICU Van". Optional.', max_length=60)),
                ('vehicle_type', models.CharField(blank=True, help_text='e.g. Basic, ALS, ICU-equipped, Mortuary van', max_length=60)),
                ('phone', models.CharField(blank=True, help_text='Number to call for this vehicle', max_length=20)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat call-out charge', max_digits=10)),
                ('per_km_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('waiting_charge_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Your own cost per trip (fuel + wear), if you track it. Leave 0 and the profit report says "not recorded" rather than reporting 100% margin.', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_TRIP', 'On a trip'), ('MAINTENANCE', 'Out of service')], default='AVAILABLE', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('registration_no',),
            },
        ),
        migrations.CreateModel(
            name='AmbulanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('licence_no', models.CharField(blank=True, max_length=40)),
                ('cnic', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_drivers', to='saas.hospital')),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='AmbulanceTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(choices=[('EMERGENCY', 'Emergency pick-up'), ('TRANSFER', 'Transfer to another facility'), ('DISCHARGE', 'Discharge / drop home'), ('BODY', 'Body transfer'), ('OTHER', 'Other')], default='EMERGENCY', max_length=12)),
                ('contact_name', models.CharField(blank=True, help_text='Who called, when there is no patient record', max_length=120)),
                ('contact_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('from_location', models.CharField(max_length=200)),
                ('to_location', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=7)),
                ('waiting_hours', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('called_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('DISPATCHED', 'Dispatched'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=12)),
                ('base_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('per_km_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('waiting_charge_per_hour', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=200)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='ambulance.ambulance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='ambulance.ambulancedriver')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_trips', to='saas.hospital')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_trips', to='billing.invoice')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulance_trips', to='patients.patient')),
            ],
            options={
                'ordering': ('-called_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='ambulance',
            name='driver',
            field=models.ForeignKey(blank=True, help_text='Usual driver — a trip can name another', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulances', to='ambulance.ambulancedriver'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='saas.hospital'),
        ),
        migrations.AddConstraint(
            model_name='ambulance',
            constraint=models.UniqueConstraint(fields=('hospital', 'registration_no'), name='uniq_ambulance_reg_per_hospital'),
        ),
    ]
