# Generated by Django 4.2.14 on 2026-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='covered_services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
