# Generated by Django 4.2.14 on 2026-07-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('sales', '0003_backfill_sale_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_sales', to='patients.patient'),
        ),
    ]
