# Generated by Django 4.2.14 on 2026-07-20 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_hospital_wholesaleorder_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
