# Generated by Django 4.2.14 on 2026-07-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_saleitem_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='needs_reconcile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='reconcile_note',
            field=models.TextField(blank=True),
        ),
    ]
