# Generated by Django 4.2.14 on 2026-08-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
        ('sales', '0009_sale_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='panels.panel'),
        ),
    ]
